### ISSUE TITLE
Not working with jQuery 2.2.0

### ISSUE THREAD

**Issue by alejandromagnorsky** [koorgoo/ngCropper#27]
When I use jQuery 2.2.0 I get this error and the ngCropper plugin doesn't work:
d.one(...).trigger is not a function

**Comment by khaledosman** [comment]
+1

**Comment by khaledosman** [comment]
+1

**Comment by dejavu1987** [comment]
+1

**Comment by alejandromagnorsky** [comment]
It seems to be working with jQuery v2.2.1
